### ISSUE TITLE
[CPV] Grande quantidade de registros Pos e Pre Trigger

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/ANAQ_2012#3]
Na usina de Capivara foi detectado grande quantidade de registros devido a configuração de Pós e Pre Trigger.

O arquivo XML foi enviado para o e-mail Felipe@md-online.com.br no 05/07/2018 já que esta interface não aceita subir arquivos no formato .xml

**Comment by felipe-coutto** [comment]
Lógica de ativação melhorada e o trigger só pode ser gerado novamente se os alarmes que o ativam pararem todos de acontecer. Correção já comitada.

**Comment by CemachMD** [comment]
Já o PATCH está disponível? Esta tarefa só poderia ser fechada após a emissão do PATCH.

**Comment by felipe-coutto** [comment]
Cesar, o patch está disponível na pasta do drive https://drive.google.com/open?id=1jg1BG9_-KkkPRvutwicyrgIkJ83xql4v
