### ISSUE TITLE
[ENGIE] Sincronizar testes ANAQ e MDM BD

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/ANAQ_2012#8]
Considerando que o PATCH já não faz a sincronização dos testes do lvlibp com o do Banco, se faz necessario termos uma aplicação para normalizar a lista de Testes nas usinas da Engie, onde se observou a falta de alguns testes pelo cliente.

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[ANAQ] Sincronização do processamento de FFT no ANAQ e noa DLL de processamento de sinais](https://trello.com/c/IneXCtK1/53-anaq-sincroniza%C3%A7%C3%A3o-do-processamento-de-fft-no-anaq-e-noa-dll-de-processamento-de-sinais)

**Comment by CemachMD** [comment]
Ao aplicar o Sincronizador, dá o seguinte erro:

![image](https://user-images.githubusercontent.com/39096287/45058435-14b40280-b06f-11e8-9bc5-a751ce20e843.png)
